spring.application.name=nagoyameshi

spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/springboot_nagoyameshi
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.encoding=utf-8
spring.sql.init.mode=always

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=3651f43b32b77a
spring.mail.password=073cff57082ea7
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.tomcat.max-part-count=20
spring.servlet.multipart.max-file-size=5MB

stripe.api-key=sk_test_51T0IBX4CXemftYL1OjvMMxS9uTwSpmdkwbioWtnOwwEupSbCiNg7I6bAdwH0bOA84XfhpxU4EgiZuSflRlxJCVO900FvOoxJUl
stripe.premium-plan-price-id=price_1TCYIz4CXemftYL19mXxZVp6

# コネクション閉じ漏れを検知して警告を出す（WARN）
# 30秒（30000ms）以上保持されたら「漏れ」とみなす
spring.datasource.hikari.leak-detection-threshold=30000